services:
  mysql:
    image: mysql
    ports:
      - "4406:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1qazzaq1
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=1qazzaq1
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"