services:
  mysql:
    image: mysql
    container_name: MysqlBuildAndRun
    environment:
      - MYSQL_USER=rafael
      - MYSQL_PASSWORD=1qazzaq1
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=1qazzaq1
    ports:
      - "4406:3306"
    expose:
      - "4406"
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
